name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  run_ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Python Script
        run: python app.py

      - name: Print Message
        run: echo "Workflow executed successfully"
