name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
    run_ci:
        runs-on: ubuntu-22.04

        steps:
           - name: Checkout Repository
             uses: actions/checkout@v4

           - name: Set up Python
             uses: actions/setup-python@v4
             with:
               python-version: '3.x'

           - name: run python script
             uses: python app.py

           - name: print message
             uses: echo "Workflow executed success fully"
